language: python
python:
 - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

script: 
- python -m pytest firstfood_test.py --cov=app
- codeclimate-test-reporter --file .coverage
  after_success:
  - coverall
